### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by gugpilot** [DiedB/Homey-TeslaEnergy#14]
Hi. I added new device, set the fixed internal ip and then when i put my user e pass i have this error. Any suggestions?
![IMG_8101](https://github.com/DiedB/Homey-TeslaEnergy/assets/30938700/02e5a6b1-d47a-4e4a-9f46-420ec4e5a349)

**Comment by gugpilot** [comment]
Any suggestions? My gateway is connected via wifi

**Comment by jonlanceley** [comment]
This is probably because you need to use:

Email address = Your registered Tesla Account email

Password = This is not your registered Tesla Account password but the last 5 characters from the sticker inside the Tesla Gateway box

See the "How to sign in" section here to find the gateway password:
https://www.tesla.com/en_gb/support/energy/powerwall/own/connecting-network

However im on a wired connection

**Comment by gugpilot** [comment]
Hi! I discovered some time ago that the issue is connected to wifi use. When wired in the lan works perfectly. Many thanks-------------------------------------------------- Guglielmo Rossi, PhDUniversità degli Studi di FirenzeCentro per la Protezione CivileLargo Enrico Fermi 2, 50125 FirenzeTel: +39 055 2755993Mobile: +39 3493268455Il giorno 26 dic 2023, alle ore 07:17, Jon lanceley ***@***.***> ha scritto:﻿
This is probably because you need to use:
Email address = Your registered Tesla Account email
Password = This is not your registered Tesla Account password but the last 5 characters from the sticker inside the Tesla Gateway box
See the "How to sign in" section here to find the gateway password:
https://www.tesla.com/en_gb/support/energy/powerwall/own/connecting-network
However im on a wired connection
