### ISSUE TITLE
Invalid credentials or session expired

### ISSUE THREAD

**Issue by wsu-runner** [DiedB/Homey-TeslaEnergy#17]
New Powerwall, trying to add to my Homey Pro '23 (10.2.0-rc.5) and unable to authenticate. Gateway version 23.36.1

Thanks.

![image](https://github.com/DiedB/Homey-TeslaEnergy/assets/136764024/7800c6e6-21a7-486d-99bd-262658433419)

**Comment by jonlanceley** [comment]
This is probably because you need to use:

Email address = Your registered Tesla Account email

Password = This is not your registered Tesla Account password but the last 5 characters from the sticker inside the Tesla Gateway box

See the "How to sign in" section here to find the gateway password:
https://www.tesla.com/en_gb/support/energy/powerwall/own/connecting-network

**Comment by DiedB** [comment]
@jonlanceley Thanks for your response! @wsu-runner did this work for you?

If these instructions are correct, I will make sure they show up on the pairing screen.

**Comment by wsu-runner** [comment]
Yes @DiedB this fixed my auth issue and I'm now able to use the app. Thanks much @jonlanceley
